//! prost-generated types for the LiveKit `agent_session` protocol
//! (`livekit.agent` package) — the `lk.agent.session` byte stream wire format.
//!
//! Generated by `build.rs` from `proto/agent/livekit_agent_session.proto`
//! (official livekit/protocol source, matching the Python
//! `livekit.protocol.agent_pb.agent_session` descriptor).
//!
//! Key types consumed by the port's agent-session observer (P3):
//! - `AgentSessionMessage` — oneof `message`: event | request | response | audio
//! - `AgentSessionEvent` — oneof `event`: function_tools_started/executed,
//!   tool_execution_updated, conversation_item_added, agent_state_changed,
//!   user_state_changed, session_usage_updated, error, overlapping_speech,
//!   debug_message, ...
//! - `SessionRequest` / `SessionResponse` — request/response correlation.

include!(concat!(env!("OUT_DIR"), "/livekit.agent.rs"));
